# Generated by Django 5.0.2 on 2024-02-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='create_at',
            field=models.DateField(auto_now_add=True, default=21),
            preserve_default=False,
        ),
    ]
