# Generated by Django 5.0.2 on 2024-02-28 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0002_carro_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='create_at',
        ),
    ]
