# Generated by Django 5.0.2 on 2024-02-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0004_alter_carro_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='capacidade',
            field=models.IntegerField(),
        ),
    ]
